# Generated by Django 3.2.12 on 2023-10-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
